[package]
name = "operator"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
rand_core = { version = "0.6", features = ["std"] }
sha2 = "0.10"
ed25519-dalek = { version = "2.1.0", features = ["rand_core", "pem"] }
hex = "0.4" # ADD THIS LINE
